img = imread('Picture1.png'); 
gray = rgb2gray(img); 
gray_filtered = medfilt2(gray, [3 3]); 
gray_eq = adapthisteq(gray_filtered); 
gmag = imgradient(gray_eq); 
se = strel('disk', 3); 
Io = imopen(gray_eq, se); 
Ie = imerode(gray_eq, se); 
Iobr = imreconstruct(Ie, gray_eq); 
Iobrd = imdilate(Iobr, se); 
Iobrcbr = imreconstruct(imcomplement(Iobrd), imcomplement(Iobr)); 
Iobrcbr = imcomplement(Iobrcbr); 
fgm = imregionalmax(Iobrcbr); 
bw = imbinarize(Iobrcbr); 
D = bwdist(~bw); 
DL = watershed(D); 
bgm = DL == 0; 
gmag2 = imimposemin(gmag, bgm | fgm); 
L = watershed(gmag2); 
tumorMask = L == 0; 
figure('Name', 'Marker-Controlled Watershed Tumor Segmentation'); 
subplot(1, 3, 1); 
imshow(gray); title('Original MRI'); 
subplot(1, 3, 2); 
imshow(gmag, []); title('Gradient Magnitude'); 
subplot(1, 3, 3); 
imshow(gray); hold on; 
h = imshow(tumorMask); 
set(h, 'AlphaData', 0.5);  
title('Watershed Tumor Segmentation'); 